### Перевірити, що сервер працює
GET http://localhost:3000/

### Отримати всі косметичні товари
GET http://localhost:3000/api/cosmetics

### Створити новий товар
POST http://localhost:3000/api/cosmetics
Content-Type: application/json

{
  "name": "Туш Lash Sensational",
  "brand": "Maybelline",
  "description": "Туш для об'єму та подовження вій",
  "price": 399
}

### Отримати товар за id
GET http://localhost:3000/api/cosmetics/6abe3dd622a4467b5273af13

### Оновити товар
PUT http://localhost:3000/api/cosmetics/6abe3dd622a4467b5273af13
Content-Type: application/json

{
  "name": "Туш Lash Sensational Sky High",
  "brand": "Maybelline",
  "description": "Оновлений опис косметичного товару",
  "price": 449
}

### Видалити товар
DELETE http://localhost:3000/api/cosmetics/6abe3ede22a4467b5273af16

### Перевірка middleware: має повернути 400 Bad Request
POST http://localhost:3000/api/cosmetics
Content-Type: application/json

{
  "name": "",
  "brand": "Test",
  "description": "Test",
  "price": 0
}
